### ISSUE TITLE
Focus does not behave properly with encoder/keypad inputs on multi-page LVGL configurations

### ISSUE THREAD

**Issue by bdm310** [OttoWinter/esphomeyaml#12146]
### The problem

**Current state**
* If you do not define any groups, everything is added to one default group including keypads and encoders
* If you define a group for a keypad or encoder, that group is added along with the default group and that input device is assigned to its specific group.
* If you do not define a group for a widget, it is added to the default group.
* If you do define a group for a widget, it is added to that group. The group must exist, defined in a keypad or encoder config.
* If you have multiple LVGL instances, you must define groups for every input and widget you want interactable.

**Valid Current Configs**
1. No pages. Assign no groups.
    * Behaves as expected.
2. No pages. Assign groups manually on each desired widget. Choose what inputs map to what groups.
    * Behaves as expected.
3. Multi-page. Assign no groups.
    * Focus will cycle through all invisible widgets as well as visible ones.
    * Can manually use hide/show on pages in actions to force expected behavior, config gets very long and confusing.
    * Can maybe use lambda to move input groups around with pages.
    * None of this is documented, behavior is very unexpected and I thought I was doing something wrong for a long time.
4. Multi-page. Assign groups manually on each desired widget. Choose what inputs map to what groups.
    * Behaves as expected, if your application is a bit weird.
5. Multiple displays, must define groups manually everywhere.
    * Behaves as expected.
    * Lots of config lines to make this work.
6. Multiple displays, multiple pages on one or more displays, must define groups manually everywhere.
    * Behaves as expected, if your application is a bit weird.
    * Lots of config lines to make this work.

* Adding a top_layer or msgbox to any of these doesn't change the individual situations.
In all cases, groups and mappings are static and cannot be changed at runtime unless you get very creative with lambda.

**Observations**
* With no specific other configuration, inputs should affect whatever on their associated screen is visible to the user and only what is visible.
    * This is how case 1/2 currently work and how I think most people would expect case 3/5/6 to work.
    * This is how touch works, by definition.
* Case 4/6 only behave as expected if you have different inputs for each page, which is a strange configuration. It degenerates to the same behavior as case 3 for normal use cases with a single input.
* Only a single page can be visible at a time, this is fundamental to how LVGL screens (esphome pages) work.
    
**Is this an LVGL bug or an Esphome bug?**
* There has never been an issued filed against LVGL for this that I can find. Not a pointer one way or the other, just context.
* There are several LVGL forum discussions about this over the past few years, none with any satisfying resolution and a couple saying that this nuance of groups and screens and etc is your job to manage as the user and not LVGL's. I don't think any of the people responding are actually representing the core LVGL team.
* There are situations where LVGL doesn't have enough context to know how you're using the provided features to correctly assign group membership. Msgbox, for instance, could be a blocking top level object that has the only valid focusable elements or it could be an addition to everything else. This is the strongest pointer to say that Esphome must handle these situations.
* This is a bug and not a feature requrest because at least one common desired config (multiple pages with only an encoder input) simply does not work as the docs or common sense have you expect.

### Which version of ESPHome has the issue?

dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

Other

### Component causing the issue

lvgl

### YAML Config

```yaml
esphome:
  name: group-test

host:

logger:

display:
  - platform: sdl
    id: disp0
    dimensions:
      width: 320
      height: 320
    auto_clear_enabled: false 

binary_sensor:
  - platform: sdl
    id: key_up2
    key: SDLK_z
    sdl_id: disp0
  - platform: sdl
    id: key_down2
    key: SDLK_c
    sdl_id: disp0
  - platform: sdl
    id: key_enter2
    key: SDLK_x
    sdl_id: disp0
          
lvgl:
  # Pages, no groups
  - id: lvgl_2
    displays: disp0
    encoders:
      enter_button: key_enter2
      sensor:
        left_button: key_up2
        right_button: key_down2
    top_layer:
      widgets:
        - label:
            text: "Top Layer"
            align: bottom_mid
        - button:
            align: bottom_left
            widgets:
              - label: 
                  text: "Next"
            on_click:
              - lvgl.page.next:
                  lvgl_id: lvgl_2
        - button:
            align: bottom_right
            widgets:
              - label: 
                  text: "Prev"
            on_click:
              then:
                - lvgl.page.previous:
                    lvgl_id: lvgl_2
    pages:
      - id: page1
        layout:
          type: flex
        widgets:
          - label:
              text: "Pages, no groups-1"
          - button:
              widgets:
                - label: 
                    text: "Next"
              on_click:
                - lvgl.page.show:
                    lvgl_id: lvgl_2
                    id: page2
          - button:
              widgets:
                - label: 
                    text: "Prev"
              on_click:
                then:
                  - lvgl.page.show:
                      lvgl_id: lvgl_2
                      id: page2
          - tabview:
              id: tabview_id
              tabs:
                - name: Dog
                  id: tabview_tab_1
                  layout:
                    type: flex
                  widgets:
                    - button:
                        widgets:
                          - label: 
                              text: "Next"
                        on_click:
                          - lvgl.page.show:
                              lvgl_id: lvgl_2
                              id: page2
                    - button:
                        widgets:
                          - label: 
                              text: "Prev"
                        on_click:
                          then:
                            - lvgl.page.show:
                                lvgl_id: lvgl_2
                                id: page2
                - name: Cat
                  id: tabview_tab_2
                  layout:
                    type: flex
                  widgets:
                    - button:
                        widgets:
                          - label: 
                              text: "Next"
                        on_click:
                          - lvgl.page.show:
                              lvgl_id: lvgl_2
                              id: page2
                    - button:
                        widgets:
                          - label: 
                              text: "Prev"
                        on_click:
                          then:
                            - lvgl.page.show:
                                lvgl_id: lvgl_2
                                id: page2
      - id: page2
        layout:
          type: flex
        widgets:
          - label:
              text: "Pages, no groups-2"
          - button:
              widgets:
                - label: 
                    text: "Next"
              on_click:
                then:
                  - lvgl.page.show:
                      lvgl_id: lvgl_2
                      id: page1
          - button:
              widgets:
                - label: 
                    text: "Prev"
              on_click:
                then:
                  - lvgl.page.show:
                      lvgl_id: lvgl_2
                      id: page1
```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by bdm310** [comment]
This issue is different from https://github.com/esphome/feature-requests/issues/3166. That feature request is specifically asking for ways to add groups and manage them explicitly in the configuration. This issue is addressing a bug in the default behavior instead.

**Comment by bdm310** [comment]
@clydebarrow, you may recall closing this the last time I brought it up and asking that it be a feature request instead. I agreed at the time but now that I've spent many more hours with the problem and implementing a solution, I am convinced it is a bug and should be fixed as such. Hopefully I've thought this through well enough and documented it clearly to convince you as well!

**Comment by clydebarrow** [comment]
So case 3, multiple pages and no explicit group configuration, I agree it doesn't behave as desired. It's not a bug in the ESPHome implementation because it's not doing anything other than passing the configuration and events to the underlying library. There are several threads in the LVGL forum documenting the same behaviour (sadly, with 9.x as well) so I'd agree it's a bug (or at least poor design), but in the LVGL library.

So I still think this is a feature request, but it really doesn't matter what it's called.

So "fixing" this in ESPHome by adding additional logic is possible, and the first thing needed is a clear idea of how it should work. There have been a couple of PRs raised that deal with this amongst other things but nothing that's currently mergeable AFAIK.

I'm currently working on moving ESPHome from LVGL 8.4 to 9.4, I'm not personally going to add new features before that's done, but if someone can produce a good PR in the meantime that addresses the issue of suppressing focus from hidden elements, I'm happy to review it.

**Comment by bdm310** [comment]
I started out agreeing with you but I do believe this falls under a higher level of functionality that I actually don't expect LVGL to address, which seems to be their approach so far as well. In fact, pages themselves are a bit of a higher level implementation specific to Esphome and this behavior is a consequence of that implementation.

I also don't care about the classification really but this is preventing me from making functional devices that I need and I don't think I'm the only one. There are some workarounds as I detail but they are really not great and fall apart in some of the edges of cases.

I submitted a new PR along with this that I believe is the cleanest way to do it while allowing for any desired future. I don't think you've had a chance to review that yet.

**Comment by clydebarrow** [comment]
> In fact, pages themselves are a bit of a higher level implementation specific to Esphome

Pages are just a rebranding of LVGL screens. I just saw the PR, will have a look, thanks.

**Comment by jimwsmith** [comment]
I also have this issue on a reasonably complex application that I am testing on M5STACK Fire devices (encoder buttons) and M5STACK CoreS3 units (touchscreen)

I have up to 6 lvgl pages some of which have focussable controls some not.  It does indeed get very confusing if you scroll focus off your current active page.  I implemented an 'I'm lost' feature on a double click of one of the encoder buttos to get you back to a known page, known focus.

**Comment by bdm310** [comment]
I'd very much appreciate more testing on the linked PR, you can easily use those changes as an external component by following the instructions in the bot response in the comments. Should be as easy as commenting out any existing group definitions you have and it will work as you expect.

**Comment by jimwsmith** [comment]
I have tested, found  few minor issues and added comments in https://github.com/esphome/esphome/pull/12147

**Comment by bdm310** [comment]
Verified that this is still an issue on dev branch. Updated the linked PR for the latest LVGL version that dev is pulling in. Review is in your hands @clydebarrow.

**Comment by bdm310** [comment]
This issue is not stale, work is ongoing in the linked PR.
