### ISSUE TITLE
Captive portal does not work when webserver auth is enabled

### ISSUE THREAD

**Issue by Steff012** [OttoWinter/esphomeyaml#12710]
### The problem

Dear, 

I already posted this issue on the webserver page [link](https://github.com/esphome/esphome-webserver/issues/167). I'm pretty sure that this is not picked up yet. hereby a new post on the main ESPhome page. 

I'm running into a strange issue with the fallback AP and captive portal in ESPHome.
When WiFi credentials are already known (either hardcoded in YAML or previously configured through the captive portal), the AP still starts correctly — but no captive portal page is shown in the browser.

```
Configuration:
wifi:
  ssid: "myssid"
  password: "mywifipassword"

  ap:
    ssid: "fallbackssid"
    password: "fallbackpassword"

captive_portal:

web_server:
  auth:
    username: "username"
    password: "password"
```
✔️ What works

When I remove all WiFi credentials from the YAML (intentional test):

The fallback AP starts
The captive portal does load correctly
I can enter WiFi credentials
Everything connects as expected
❌ What does not work

If the device already knows valid WiFi credentials (either:

defined in YAML, or
set once via captive portal):
Disconnect main WiFi

The fallback AP starts
But the captive portal does NOT appear
Browsers show only a blank page or nothing loads
Tested on Windows, Android, Chrome, Edge, Firefox
What I’ve tried

Multiple ESP devices (ESP8266, ESP32)
Multiple configurations (with/without YAML WiFi credentials)
Tested many browsers and devices:
Chrome, Edge, Firefox
Windows & Android
Clearing DNS cache on device and browser
Power cycling
Same result every time.

📝 Summary

It looks like the captive portal only works the first time, when no credentials are known yet.
Once WiFi credentials have been stored, the AP still appears — but captive portal is no longer available.

### Which version of ESPHome has the issue?

2025.11.5

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

captive_portal

### YAML Config

```yaml
Configuration:
wifi:
  ssid: "myssid"
  password: "mywifipassword"

  ap:
    ssid: "fallbackssid"
    password: "fallbackpassword"

captive_portal:

web_server:
  auth:
    username: "username"
    password: "password"
```

### Anything in the logs that might be useful for us?

``` nope

```

### Additional information

Additional information on ESPhome version 2025.10.5 te captive portal still works as expected.
I guess it is a bug in the ESP 2025.11 / 2025.12 versions.

**Comment by platima** [comment]
Same issue here. Did not realise until I deployed it somewhere very hard to get to again!

Going to go back now and jump on the hotspot to see if I can at least get to /events to read the data.

Else I might try to mimic the AP it's meant to connect to.

**Comment by Steff012** [comment]
I'm terrified of updating ESPhome because of this issue. The developers haven't responded to this issue yet.

**Comment by platima** [comment]
> I'm terrified of updating ESPhome because of this issue. The developers haven't responded to this issue yet.

I've just got it installed standalone, not in Home Assistant, but if it's any consolation I just did a build on an ESP32-C3 using IDF and the web page is working fine. Have not tested the captive portal yet though sorry!

**Comment by bdraco** [comment]
I tested the captive portal on 2025.12.5, 2026.1.0b1, and 2026.1.0b2 across ESP32, ESP8266, and LibreTiny platforms and was unable to reproduce this issue. The captive portal displayed correctly when falling back to AP mode with existing WiFi credentials configured.

Could you please provide serial logs from when the device boots up and enters fallback AP mode? This would help identify what's happening when the captive portal fails to load.

**Comment by platima** [comment]
I can't get to the one I have deployed to reset it either, but I'll have a team collect it next week and then I can grab the serial logs for you before updating and re-deploying it.

For what it's worth, I got the data I needed by navigating to /events in the captive portal and getting the feed.

Cheers

**Comment by Steff012** [comment]
This morning ran some tests on my HA testsystem with the latest ESPhome 2025.12.7
Created a new device with the following code:

```
esphome:
  name: captive-test
  friendly_name: Captive_test

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

api:
  encryption:
    key: "/Dk3iouayWuZQxDXmbwpxOP9+DTMFSKd1yE8SAiT25o="

ota:
  - platform: esphome
    password: "d7de843396295981bf08b63920346f7d"

wifi:
  ssid: "Justatest"
  password: "Justatest"

  ap:
    ssid: "Justatest"
    password: "Justatest"

captive_portal:

web_server:
```

The results are the same, Captive AP starts up. I can connect with the AP wifi, but the display stays empty. No wifi cridentials can be setup.

![Image](https://github.com/user-attachments/assets/cfeca3a4-2108-452d-8f08-dc77d73b7e90)

Find the log of the unit here:
[logs.txt](https://github.com/user-attachments/files/24735205/logs.txt)

**Comment by platima** [comment]
Ah thanks for that - that's exactly what I get too!

I think you meant 2025.12.7 though, not 2026?

**Comment by Steff012** [comment]
whoops, of course! 
2025.12.7, edited in my comment.

**Comment by Steff012** [comment]
I noticed the following change in the ESPHome 2026.1.0 changelog:

[wifi] Fix captive portal/improv only attempting last configured network
[esphome#13086](https://github.com/esphome/esphome/pull/13086)

Today I tested with ESPHome 2026.1.0, but unfortunately the issue persists.
The fallback AP starts, however the captive portal is still not accessible once WiFi credentials are known.

**Comment by Steff012** [comment]
Update: version 2026.1.5 still not solved.

**Comment by Steff012** [comment]
Update: version 2026.2.0 still not solved.

**Comment by viteo** [comment]
faced same problem today on latest 2026.2.2
<details>
<summary>Log</summary>
<RTL8195A>ROM:[V0.1]
FLASHRATE:4
BOOT TYPE:0 XTAL:40000000
IMG1 DATA[1168:10002000]
IMG1 ENTRY[8000541:100021ef]
IMG1 ENTER
CHIPID[000000ff]
read_mode idx:0, flash_speed idx:0
calibration_result:[1:7:11][7:d] 
calibration_result:[2:13:7][1:d] 
calibration_result:[3:3:3][1:3] 
calibration_ok:[2:13:7] 
FLASH CALIB[NEW OK]
OTA2 ADDR[80d0000]
OTAx SELE[fffffffc]
OTA1 USE
IMG2 DATA[0x808e0e0:4204:0x10005000]
IMG2 SIGN[RTKWin(10005008)]
IMG2 ENTRY[0x10005000:0x803e169]
System_Init1
System_Init2
I [      0.000] LibreTiny v1.12.1+sha.73564e9 on wr2, compiled at Feb 27 2026 13:10:42, GCC 10.3.1 (-Os)
[I][logger:049]: Log initialized
[C][safe_mode:123]: Unsuccessful boot attempts: 0
[D][lt.preferences:144]: Writing 1 items: 0 cached, 1 written, 0 failed
[I][app:091]: Running through setup()
[D][switch:026]: 'Relay' Turning OFF.
[D][switch:065]: 'Relay' >> OFF
[D][switch:026]: 'Relay' Turning OFF.
[D][status_led:039]: 'statusled': Setting initial state
[D][status_led:050]: 'statusled': Setting state OFF
[D][light:079]: 'statusled' Setting:
[D][light:085]:   Color mode: On/Off
[C][wifi:610]: Starting
interface 0 is initialized
interface 1 is initialized

Initializing WIFI ...
WIFI initialized
[D][wifi:1263]: Starting scan
[C][component:278]: Setup wifi took 178ms
[W][component:422]: api set Warning flag: unspecified
[I][app:138]: setup() finished successfully!
[D][binary_sensor:044]: 'Button' >> OFF
[W][component:431]: wifi set Warning flag: scanning for networks
[I][app:215]: ESPHome version 2026.2.2 compiled on 2026-02-27 13:06:50 +0300
[C][logger:237]: Logger:
  Max Level: DEBUG
  Initial Level: DEBUG
[C][logger:244]:   Log Baud Rate: 115200
  Hardware UART: UART2
[C][logger:254]:   Task Log Buffer Size: 768 bytes
[C][switch.gpio:092]: GPIO Switch 'Relay'
  Restore Mode: restore defaults to OFF
[C][switch.gpio:152]:   Pin: 0
[C][status_led:063]: Status Led Light:
[C][status_led:152]:   Pin: 23
[C][gpio.binary_sensor:016]: GPIO Binary Sensor 'Button'
[C][gpio.binary_sensor:152]:   Pin: 18
[C][gpio.binary_sensor:069]:   Mode: polling
[C][light:091]: Light 'statusled'
[C][captive_portal:134]: Captive Portal:
[C][wifi:1450]: WiFi:
  Local MAC: 68:57:2D:D1:49:5E
  Connected: NO
[C][web_server:424]: Web Server:
  Address: yndx-007.local:80
[C][esphome.ota:075]: Over-The-Air updates:
  Address: yndx-007.local:8892
  Version: 2
[C][esphome.ota:082]:   Password configured
[C][safe_mode:022]: Safe Mode:
  Successful after: 60s
  Invoke after: 10 attempts
  Duration: 300s
[C][web_server.ota:238]: Web Server OTA
[C][api:237]: Server:
  Address: yndx-007.local:6053
  Listen backlog: 4
  Max connections: 8
[C][api:244]:   Noise encryption: YES
[C][mdns:177]: mDNS:
  Hostname: yndx-007
[C][lt.component:013]: LibreTiny:
  Version: v1.12.1+sha.73564e9 on wr2, compiled at Feb 27 2026 13:08:20, GCC 10.3.1 (-Os)
  Loglevel: 3
[W][wifi:1377]: No networks found
[D][wifi:1739]: Retry phase: INITIAL_CONNECT → SCAN_CONNECTING
[D][wifi:1263]: Starting scan
[W][wifi:1377]: No networks found
[D][wifi:1739]: Retry phase: SCAN_CONNECTING → RETRY_HIDDEN
[D][wifi:540]: Hidden candidate 'viteos22u' at index 0
[I][wifi:1064]: Connecting to 'viteos22u' (any) (priority 0, attempt 1/1 in phase RETRY_HIDDEN)...
E [      4.196] WIFI: Connection failed; ret=-1
[W][wifi_lt:220]: esp_wifi_connect failed: 4
[E][wifi:1141]: wifi_sta_connect_ failed
[W][component:579]: wifi took a long time for an operation (1345 ms)
[W][component:582]: Components should block for at most 30 ms
[D][lt.preferences:138]: FDB data not changed; skipping 3551080420  len=1
[D][lt.preferences:144]: Writing 1 items: 1 cached, 0 written, 0 failed
[W][wifi:1550]: Connection timeout, aborting connection attempt
[D][wifi:1739]: Retry phase: RETRY_HIDDEN → RESTARTING
[W][wifi:701]: Restarting adapter

LwIP_DHCP: dhcp stop.
Deinitializing WIFI ...
WIFI deinitialized[D][hlw8012:076]: Got power=0.0W, current=0.0A
[W][wifi_lt:514]: Disconnected ssid='' bssid=00:00:00:00:00:00 reason='Unspecified'
[W][wifi:1582]: Unknown connection status 0
[D][wifi:1739]: Retry phase: RESTARTING     SCAN_CONNECTING
[D][wifi:1263]: Starting scan

Initializing WIFI ...
WIFI initialized
[W][wifi:1377]: No networks found
[D][wifi:1739]: Retry phase: SCAN_CONNECTING → RETRY_HIDDEN
[D][wifi:540]: Hidden candidate 'viteos22u' at index 0
[I][wifi:1064]: Connecting to 'viteos22u' (any) (priority 0, attempt 1/1 in phase RETRY_HIDDEN)...
E [     53.735] WIFI: Connection failed; ret=-1
[W][wifi_lt:220]: esp_wifi_connect failed: 4
[E][wifi:1141]: wifi_sta_connect_ failed
[I][safe_mode:071]: Boot seems successful; resetting boot loop counter
[D][lt.preferences:144]: Writing 1 items: 0 cached, 1 written, 0 failed
[I][wifi:798]: Starting fallback AP

LwIP_DHCP: dhcp stop.
Deinitializing WIFI ...
WIFI deinitialized
Initializing WIFI ...
WIFI initialized
E [     91.807] WIFI: Connection failed; ret=-1
[C][wifi:925]: Setting up AP:
  AP SSID: 'yndx-007 Fallback Hotspot'
  AP Password: ''
  IP Address: 192.168.4.1
[W][component:579]: wifi took a long time for an operation (1777 ms)
[W][component:582]: Components should block for at most 30 ms
[W][wifi_lt:494]: Too many disconnect events (3) while connecting, treating as failure (reason=Unspecified)
[W][wifi_lt:514]: Disconnected ssid='' bssid=00:00:00:00:00:00 reason='Unspecified'
[W][wifi:1560]: Connecting to network failed (callback)
[D][wifi:1739]: Retry phase: RETRY_HIDDEN → RESTARTING
ip_table[100] = 0,0,0,0,0,0

[112118] DHCP assign ip = 192.168.4.100
E [    124.582] WIFI: Connection failed; ret=-1
[W][wifi_lt:220]: esp_wifi_connect failed: 4
[E][wifi:1141]: wifi_sta_connect_ failed

[I][wifi:1064]: Connecting to 'viteos22u' (any) (priority 0, attempt 1/1 in phase RETRY_HIDDEN)...
E [    434.073] WIFI: Connection failed; ret=-1
[W][wifi_lt:220]: esp_wifi_connect failed: 4
[E][wifi:1141]: wifi_sta_connect_ failed
etc...
</details>

it creates a Fallback Hotspot but still tries to reconnect to the configured ssid.

**Comment by ssieb** [comment]
@Steff012 are you sure this isn't an issue with your phone?  It doesn't get internet access from the wifi, so it might not use that.  Try disabling data and see what happens.

> it creates a Fallback Hotspot but still tries to reconnect to the configured ssid.

Of course.  If the configured wifi comes back up, it should connect.

**Comment by viteo** [comment]
After rolling back to my previous image 2025.3.3, the captive portal is displayed correctly. 🤔

**Comment by Steff012** [comment]
@ssieb, It happens with any device, smartphone and also laptop (see TS: Tested on Windows, Android, Chrome, Edge, Firefox). So yes, I've tried.

@viteo, the EPShome version up to 2025.10.5 the captive protal still works as expected.

@bdraco, did you take a look at the log?

**Comment by kvanbiesen** [comment]
Same here. Weird thing it. It worked the first time but first time the wifi goes out and the captive portal should kick in, I get white page. 

//yeah exact same stuff. Works once, then it gives blank page when connectin to the fallback;
I tried reverting to older ESP-IDF but didnt help much.

**Comment by bdraco** [comment]
> [@bdraco](https://github.com/bdraco), did you take a look at the log?

Yes, nothing stands out.

I still can't reproduce the issue. I've tried ESP32 classic, ESP32S3, ESP32C3, ESP8266. All work as expected for me

**Comment by bdraco** [comment]
Taking a guess here, but I think the key is to add web_server to the config as well.   Maybe a regression from #9823

The timeline lines up

**Comment by bdraco** [comment]
another test but working fine
```yaml
esphome:
  name: captive-test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

wifi:
  ssid: "nonexistent_network"
  password: "doesntmatter"
  ap:
    ssid: "CaptiveTest"
    password: ""

captive_portal:

web_server:

logger:
```

**Comment by bdraco** [comment]
ok adding auth is getting somewhere
```yaml
esphome:
  name: captive-test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

wifi:
  ssid: "nonexistent_network"
  password: "doesntmatter"
  ap:
    ssid: "CaptiveTest"
    password: ""

captive_portal:

web_server:
  auth:
    username: "admin"
    password: "admin"

logger:
```

**Comment by kvanbiesen** [comment]
This is my code that also has it. No auth and also has the same issue...

```
esphome:
  name: boiler-controller
  friendly_name: "Boiler Solar Controller"
  min_version: 2026.1.0 # Ensures watchdog_timeout and other features are
available

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_LWIP_TCP_MSL: "5000" # Reduces TIME_WAIT period so sockets
release faster
      CONFIG_LWIP_TCP_FIN_WAIT_TIMEOUT: "5000" # Reduces FIN_WAIT timeout
so sockets release faster

wifi:
  power_save_mode: none
  on_connect:
    - logger.log: "WiFi connected"
  on_disconnect:
    - logger.log: "WiFi lost — will reconnect automatically"
    - lambda: |-
        // Kill boiler if WiFi drops — can't read P1 without it
        id(boiler_pwm).set_level(0);
        id(g_duty) = 0.0f;
  ap:
    ssid: "Boiler-Setup"
    password: "12345678"
    ap_timeout: 15min # 15min gives enough time to connect, open browser
and reconfigure WiFi

captive_portal:

logger:
  level: INFO

api:
  reboot_timeout: 0s # Disable auto-reboot when HA client disconnects

json:

ota:
  - platform: esphome

improv_serial: # Allows WiFi config via USB serial if captive portal is
unreachable

web_server:
  port: 80
  version: 2

```

**Comment by bdraco** [comment]
Looks like that is a different issue. I can reproduce the issue with auth. Since that's what the op's issue is, I'm going to focus on fixing that

**Comment by kvanbiesen** [comment]
I'll see what this gives, maybe it get fixed by the same solution since my symptoms are exact the same. (Besides having no auth)

**Comment by platima** [comment]
Woooo!
