### ISSUE TITLE
ESP32-C6 (IDF) fails to boot on 2025.6 /w I2C and `scan: true`

### ISSUE THREAD

**Issue by ireun** [OttoWinter/esphomeyaml#9763]
### The problem

Compilation is fine, but EspHome 2025.6.0 bootloops with I2C scan being enabled. It was working on version prior to 2025.6.0 though. Adding `scan: false` to I2C section results in successful boot. 

### Which version of ESPHome has the issue?

2025.6.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Board

ESP32-C6-WROOM-1-N16

### YAML Config

```yaml
esphome:
  name: "esphome-esp32c6-sypialnia"
  friendly_name: Sypialnia

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

i2c:
  scl: 6
  sda: 5
#  scan: false

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXX"

ota:
  - platform: esphome
    password: "XXX"

wifi:
  domain: ""
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32C6 Fallback Hotspot"
    password: "XXX"

captive_portal:

esp32_ble_tracker:

ble_client:
  - mac_address: XXX
    id: oclean

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      accuracy_decimals: 2
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
      oversampling: 16x
    humidity:
      name: "BME280 Humidity"
      oversampling: 16x
    address: 0x76
    update_interval: 10s
    iir_filter: 16x
  - platform: ble_client
    type: characteristic
    ble_client_id: oclean
    name: "Oclean Air"
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    device_class: "battery"
    unit_of_measurement: "%"
```

### Anything in the logs that might be useful for us?

```txt
[13:29:49]ESP-ROM:esp32c6-20220919
[13:29:49]Build:Sep 19 2022
[13:29:49]rst:0x15 (USB_UART_HPSYS),boot:0x6f (SPI_FAST_FLASH_BOOT)
[13:29:49]Saved PC:0x42075514
[13:29:49]SPIWP:0xee
[13:29:49]mode:DIO, clock div:2
[13:29:49]load:0x40875720,len:0x18ec
[13:29:49]load:0x4086c110,len:0xd9c
[13:29:49]load:0x4086e610,len:0x2f80
[13:29:49]entry 0x4086c110
[13:29:49]I (23) boot: ESP-IDF 5.3.2 2nd stage bootloader
[13:29:49]I (23) boot: compile time Jun 18 2025 13:28:59
[13:29:49]I (24) boot: chip revision: v0.0
[13:29:49]I (24) boot: efuse block revision: v0.2
[13:29:49]I (24) boot.esp32c6: SPI Speed      : 80MHz
[13:29:49]I (25) boot.esp32c6: SPI Mode       : DIO
[13:29:49]I (25) boot.esp32c6: SPI Flash Size : 16MB
[13:29:49]I (26) boot: Enabling RNG early entropy source...
[13:29:49]I (27) boot: Partition Table:
[13:29:49]I (27) boot: ## Label            Usage          Type ST Offset   Length
[13:29:49]I (28) boot:  0 otadata          OTA data         01 00 00009000 00002000
[13:29:49]I (29) boot:  1 phy_init         RF data          01 01 0000b000 00001000
[13:29:49]I (30) boot:  2 app0             OTA app          00 10 00010000 007c0000
[13:29:49]I (31) boot:  3 app1             OTA app          00 11 007d0000 007c0000
[13:29:49]I (32) boot:  4 nvs              WiFi data        01 02 00f90000 0006d000
[13:29:49]I (33) boot: End of partition table
[13:29:49]I (33) esp_image: segment 0: paddr=00010020 vaddr=42140020 size=44dbch (282044) map
[13:29:49]I (87) esp_image: segment 1: paddr=00054de4 vaddr=40800000 size=0b234h ( 45620) load
[13:29:49]I (97) esp_image: segment 2: paddr=00060020 vaddr=42000020 size=1319e0h (1251808) map
[13:29:49]I (328) esp_image: segment 3: paddr=00191a08 vaddr=4080b234 size=169e0h ( 92640) load
[13:29:49]I (356) boot: Loaded app from partition at offset 0x10000
[13:29:49]I (357) boot: Disabling RNG early entropy source...
[13:29:49]I (358) cpu_start: Unicore app
[13:29:49]I (366) cpu_start: Pro cpu start user code
[13:29:49]I (366) cpu_start: cpu freq: 160000000 Hz
[13:29:49]I (367) app_init: Application information:
[13:29:49]I (367) app_init: Project name:     esphome-esp32c6-sypialnia
[13:29:49]I (368) app_init: App version:      2025.6.0
[13:29:49]I (369) app_init: Compile time:     Jun 18 2025 13:27:49
[13:29:49]I (370) app_init: ELF file SHA256:  a87450e65...
[13:29:49]I (370) app_init: ESP-IDF:          5.3.2
[13:29:49]I (371) efuse_init: Min chip rev:     v0.0
[13:29:49]I (371) efuse_init: Max chip rev:     v0.99 
[13:29:49]I (372) efuse_init: Chip rev:         v0.0
[13:29:49]I (372) heap_init: Initializing. RAM available for dynamic allocation:
[13:29:49]I (373) heap_init: At 4082B290 len 00051380 (324 KiB): RAM
[13:29:49]I (374) heap_init: At 4087C610 len 00002F54 (11 KiB): RAM
[13:29:49]I (375) heap_init: At 50000000 len 00003FE8 (15 KiB): RTCRAM
[13:29:49]I (377) spi_flash: detected chip: generic
[13:29:49]I (377) spi_flash: flash io: dio
[13:29:49]W (377) i2c: This driver is an old driver, please migrate your application code to adapt `driver/i2c_master.h`
[13:29:49]I (378) sleep: Configure to isolate all GPIO pins in sleep state
[13:29:49]I (379) sleep: Enable automatic switching of GPIO sleep configuration
[13:29:49]I (380) coexist: coex firmware version: cbb41d7
[13:29:49]I (381) coexist: coexist rom version 5b8dcfa
[13:29:49]I (381) main_task: Started on CPU0
[13:29:49]I (381) main_task: Calling app_main()
[13:29:49][I][logger:171]: Log initialized
[13:29:49][C][safe_mode:080]: There have been 5 suspected unsuccessful boot attempts
[13:29:49][D][esp32.preferences:142]: Writing 1 items: 0 cached, 1 written, 0 failed
[13:29:49][I][app:048]: Running through setup()
[13:29:49][C][i2c.idf:021]: Running setup
[13:29:49][I][i2c.idf:262]: Performing bus recovery
[13:29:49][D][esp-idf:000]: I (479) gpio: GPIO[6]| InputEn: 1| OutputEn: 1| OpenDrain: 1| Pullup: 1| Pulldown: 0| Intr:0 
[13:29:49][D][esp-idf:000]: I (480) gpio: GPIO[5]| InputEn: 1| OutputEn: 1| OpenDrain: 1| Pullup: 1| Pulldown: 0| Intr:0 
[13:29:54]E (5479) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
[13:29:54]E (5479) task_wdt:  - loopTask (CPU 0)
[13:29:54]E (5479) task_wdt: Tasks currently running:
[13:29:54]E (5479) task_wdt: CPU 0: loopTask
[13:29:54]E (5479) task_wdt: Aborting.
[13:29:54]
[13:29:54]
[13:29:54]Core  0 register dump:
[13:29:54]MEPC    : 0x42075518  RA      : 0x42076626  SP      : 0x408336c0  GP      : 0x4081e7e4  
[13:29:54]TP      : 0x408337e0  T0      : 0x00000000  T1      : 0x400001fe  T2      : 0xffffffff  
[13:29:54]S0/FP   : 0x00000000  S1      : 0x4082dd04  A0      : 0x00000000  A1      : 0x4082de28  
[13:29:54]A2      : 0x00000001  A3      : 0x00000800  A4      : 0x00000013  A5      : 0x60004000  
[13:29:54]A6      : 0x00000004  A7      : 0x00000014  S2      : 0x00000000  S3      : 0x0000007d  
[13:29:54]S4      : 0x00000014  S5      : 0x00000069  S6      : 0x000003e8  S7      : 0x00000002  
[13:29:54]S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000  
[13:29:54]T3      : 0x40827000  T4      : 0x00000001  T5      : 0x40827000  T6      : 0x00000001  
[13:29:54]MSTATUS : 0x00000000  MTVEC   : 0x00000000  MCAUSE  : 0x4082de54  MTVAL   : 0x00000001  
[13:29:54]MHARTID : 0x00000004  
[13:29:54]
[13:29:54]Stack memory:
[13:29:54]408336c0: 0x00000000 0x00000000 0x4082de54 0x00000001 0x00000004 0x00000000 0x00000001 0x4082d680
[13:29:54]408336e0: 0x00000000 0x00000000 0x4082de54 0x4201003e 0x00000000 0x00000001 0x00000006 0x00000078
[13:29:54]40833700: 0x4082d684 0x4082d680 0x0000001b 0x420101c6 0x00000001 0x408273ac 0x4081e0c4 0x421b58e6
[13:29:54]40833720: 0x00000004 0x00000008 0x42144000 0x4082d694 0x00000001 0x42143000 0x4082d680 0x420104d0
[13:29:54]40833740: 0x40821c38 0x00000001 0x00000005 0x00000006 0x00000101 0x0000c350 0x00000000 0x00000000
[13:29:54]40833760: 0x00000001 0x408339b0 0x40821c38 0x42019d24 0x00000000 0x00000008 0x00000008 0x4082dd04
[13:29:54]40833780: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[13:29:54]408337a0: 0x00000000 0x00000000 0x00000000 0x4200a198 0x00000000 0x00000000 0x00000000 0x00000000
[13:29:54]408337c0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
[13:29:54]408337e0: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000150 0x40833640 0x0000007d 0x408227f4 0x408227f4
[13:29:54]40833800: 0x408337f0 0x408227ec 0x00000018 0x4082ddf8 0x4082ddf8 0x408337f0 0x00000000 0x00000001
[13:29:54]40833820: 0x408317ec 0x706f6f6c 0x6b736154 0x00000000 0x00000000 0x408337e0 0x00000001 0x00000001
[13:29:54]40833840: 0x00000000 0x00000000 0x00000000 0x4082bcc8 0x4082bd30 0x4082bd98 0x00000000 0x00000000
[13:29:54]40833860: 0x00000001 0x00000000 0x00000000 0x00000000 0x4209a8de 0x00000000 0x00000000 0x00000000
[13:29:54]40833880: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[13:29:54]408338a0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[13:29:54]408338c0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[13:29:54]408338e0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[13:29:54]40833900: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[13:29:54]40833920: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[13:29:54]40833940: 0x00000010 0x4082d940 0x4082d98c 0x4082d9d8 0x4082da24 0x0000000c 0x40833968 0x00000000
[13:29:54]40833960: 0x40833950 0x0000000c 0x0c160008 0x00000000 0x4082de44 0x00000010 0x00000000 0x408337f0
[13:29:54]40833980: 0x00000000 0x00000000 0x00000020 0x68707365 0x2d656d6f 0x33707365 0x2d366332 0x69707973
[13:29:54]408339a0: 0x696e6c61 0x77650061 0x40833984 0x0000003c 0x408339f0 0x4082d694 0x4082d6dc 0x4082d8c0
[13:29:54]408339c0: 0x4082da6c 0x4082db18 0x4082d710 0x4082d7f4 0x408345b8 0x40834638 0x40834670 0x4083494c
[13:29:54]408339e0: 0x408349fc 0x4082d504 0x408348ec 0x00000088 0x42168c18 0x4082b201 0x7fc00000 0x42143284
[13:29:54]40833a00: 0x5b5d0032 0x40833a0c 0x00000000 0x43203a00 0x656e6e6f 0x64657463 0x6d305b1b 0x0001c200
[13:29:54]40833a20: 0x40833a7c 0x00000085 0x00000200 0x00000003 0x00000000 0x6f4c2020 0x00000000 0x00000000
[13:29:54]40833a40: 0x40833a38 0x40833a38 0x00000000 0x00000000 0x00000000 0x00000000 0x00000005 0x40833c84
[13:29:54]40833a60: 0x775b5d00 0x00000003 0x00000000 0x00000000 0x00000000 0x408337f0 0x00000204 0x3b305b1b
[13:29:54]40833a80: 0x5b6d3633 0x655b5d44 0x692d7073 0x303a6664 0x3a5d3030 0x305b1b20 0x6d32333b 0x34282049
[13:29:54]40833aa0: 0x20293038 0x6f697067 0x5047203a 0x355b4f49 0x49207c5d 0x7475706e 0x203a6e45 0x4f207c31
[13:29:54]
[13:29:54]
[13:29:54]
[13:29:54]ELF file SHA256: a87450e65
[13:29:54]
[13:29:54]Rebooting...
[13:29:54]ESP-ROM:esp32c6-20220919
[13:29:54]Build:Sep 19 2022
[13:29:54]rst:0xc (SW_CPU),boot:0x6f (SPI_FAST_FLASH_BOOT)
[13:29:54]Saved PC:0x4001975a
[13:29:54]SPIWP:0xee
[13:29:54]mode:DIO, clock div:2
[13:29:54]load:0x40875720,len:0x18ec
[13:29:54]load:0x4086c110,len:0xd9c
[13:29:54]load:0x4086e610,len:0x2f80
[13:29:54]entry 0x4086c110
```

**Comment by bdraco** [comment]
https://esphome.io/guides/troubleshooting.html#getting-a-stack-trace-from-crashes

**Comment by Hunter32R** [comment]
The problem with I2C is also on H2.

```
E (5802) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
E (5802) task_wdt:  - loopTask (CPU 0)
E (5802) task_wdt: Tasks currently running:
E (5802) task_wdt: CPU 0: loopTask
E (5802) task_wdt: Aborting.


Core  0 register dump:
MEPC    : 0x4201d938  RA      : 0x4201ea62  SP      : 0x4081f3b0  GP      : 0x4080d444
TP      : 0x4081f4d0  T0      : 0x00000000  T1      : 0x400006f6  T2      : 0x6e457475
S0/FP   : 0x00000000  S1      : 0x40819c24  A0      : 0x00000000  A1      : 0x40819d48
A2      : 0x00000001  A3      : 0x00000800  A4      : 0x00000013  A5      : 0x60004000
A6      : 0x00000004  A7      : 0x00000014  S2      : 0x00000000  S3      : 0x000000d9
S4      : 0x00000014  S5      : 0x000000c5  S6      : 0x000003e8  S7      : 0x00000002
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
T3      : 0x40817000  T4      : 0x00000001  T5      : 0x40817000  T6      : 0x00000001
MSTATUS : 0x00000000  MTVEC   : 0x00000000  MCAUSE  : 0x40819d74  MTVAL   : 0x00000001
MHARTID : 0x00000004

Stack memory:
4081f3b0: 0x00000000 0x00000000 0x40819d74 0x00000001 0x00000004 0x00000000 0x00000001 0x40819460
4081f3d0: 0x00000000 0x00000000 0x40819d74 0x420093c0 0x00000000 0x00000001 0x00000006 0x00000078
4081f3f0: 0x40819464 0x40819460 0x0000001b 0x4200953c 0x00000000 0x00000000 0x00000000 0x001b0002
4081f410: 0x00000004 0x00000008 0x420b2000 0x40819474 0x00000001 0x420b1000 0x40819460 0x42009852
4081f430: 0x4080e7ec 0x00000001 0x0000001b 0x0000001a 0x00000101 0x0000c350 0x00000000 0x00000000
4081f450: 0x00000001 0x4081f66c 0x4080e7ec 0x4200f602 0x40819bb4 0x0000000a 0x0000000a 0x40819c24
4081f470: 0xf0b54a8d 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f490: 0x00000000 0x00000000 0x00000000 0x420079fa 0x00000000 0x00000000 0x00000000 0x00000000
4081f4b0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
4081f4d0: 0xa5a5a5a5 0x00000150 0x4081f330 0x000000d9 0x4080f47c 0x4080f47c 0x4081f4d8 0x4080f474
4081f4f0: 0x00000018 0x40819d18 0x40819d18 0x4081f4d8 0x00000000 0x00000001 0x4081d4d4 0x706f6f6c
4081f510: 0x6b736154 0x00000000 0x00000000 0x4081f4d0 0x00000001 0x00000001 0x00000000 0x00000000
4081f530: 0x00000000 0x40817cb8 0x40817d20 0x40817d88 0x00000000 0x00000000 0x00000001 0x00000000
4081f550: 0x00000000 0x00000000 0x42043678 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f570: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f590: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f5b0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f5d0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f5f0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f610: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000028 0x408195fc
4081f630: 0x408196ac 0x40819748 0x408197e4 0x40819884 0x40819924 0x408199c0 0x40819a70 0x40819b18
4081f650: 0x40819bb4 0x00000010 0x00000000 0x4081f4d8 0x00000000 0x00000000 0x00000050 0x4081f6c0
4081f670: 0x40819474 0x408194bc 0x4081956c 0x408194f0 0x408207e0 0x40820884 0x408192c4 0x408195cc
4081f690: 0x4081967c 0x40819718 0x408197b4 0x40819854 0x408198f4 0x40819990 0x40819a40 0x40819ae8
4081f6b0: 0x40819b84 0x40820780 0x40819520 0x00000088 0x420c7978 0x40817101 0x7fc00000 0x420b158c
4081f6d0: 0xb87e0032 0x4081f6dc 0x00000000 0x33e5da00 0xd6fc1b4d 0x76393a43 0xc20538e3 0x0001c200
4081f6f0: 0x4081f74c 0x00000086 0x00000200 0x00000000 0x00000000 0x4b5cf99f 0x00000000 0x00000000
4081f710: 0x4081f708 0x4081f708 0x00000000 0x00000000 0x00000000 0x00000000 0x00000005 0x4081f954
4081f730: 0x9ce32c00 0x00000003 0x00000000 0x00000000 0x00000000 0x4081f4d8 0x00000204 0x3b305b1b
4081f750: 0x5b6d3633 0x655b5d44 0x692d7073 0x303a6664 0x3a5d3030 0x305b1b20 0x6d32333b 0x38282049
4081f770: 0x20293630 0x6f697067 0x5047203a 0x325b4f49 0x207c5d37 0x75706e49 0x3a6e4574 0x207c3120
4081f790: 0x7074754f 0x6e457475 0x7c31203a 0x65704f20 0x6172446e 0x203a6e69 0x50207c31 0x756c6c75



ELF file SHA256: cc4bb1eb4

Rebooting...
ESP-ROM:esp32h2-20221101
Build:Nov  1 2022
rst:0xc (SW_CPU),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x400031b6
SPIWP:0xee
mode:DIO, clock div:1
load:0x408460e0,len:0x1894
load:0x4083cad0,len:0xf20
load:0x4083efd0,len:0x2dc0
entry 0x4083cad0
I (27) boot: ESP-IDF 5.3.2 2nd stage bootloader
I (27) boot: compile time Jun 19 2025 15:11:14
I (29) boot: chip revision: v0.1
I (30) boot: efuse block revision: v0.1
I (34) boot.esp32h2: SPI Speed      : 64MHz
I (39) boot.esp32h2: SPI Mode       : DIO
I (44) boot.esp32h2: SPI Flash Size : 4MB
I (48) boot: Enabling RNG early entropy source...
I (54) boot: Partition Table:
I (57) boot: ## Label            Usage          Type ST Offset   Length
I (65) boot:  0 otadata          OTA data         01 00 00009000 00002000
I (72) boot:  1 phy_init         RF data          01 01 0000b000 00001000
I (80) boot:  2 app0             OTA app          00 10 00010000 001c0000
I (87) boot:  3 app1             OTA app          00 11 001d0000 001c0000
I (94) boot:  4 nvs              WiFi data        01 02 00390000 0006d000
I (102) boot: End of partition table
I (107) esp_image: segment 0: paddr=00010020 vaddr=420b0020 size=277e8h (161768) map
I (181) esp_image: segment 1: paddr=00037810 vaddr=40800000 size=08808h ( 34824) load
I (199) esp_image: segment 2: paddr=00040020 vaddr=42000020 size=aa978h (698744) map
I (485) esp_image: segment 3: paddr=000ea9a0 vaddr=40808808 size=04434h ( 17460) load
I (495) esp_image: segment 4: paddr=000eeddc vaddr=4080cc40 size=01b98h (  7064) load
I (507) boot: Loaded app from partition at offset 0x10000
I (508) boot: Disabling RNG early entropy source...
I (520) cpu_start: Unicore app
I (528) cpu_start: Pro cpu start user code
I (529) cpu_start: cpu freq: 96000000 Hz
I (529) app_init: Application information:
I (531) app_init: Project name:     socket-thread
I (537) app_init: App version:      2025.6.0
I (542) app_init: Compile time:     Jun 19 2025 15:09:35
I (548) app_init: ELF file SHA256:  cc4bb1eb4...
I (553) app_init: ESP-IDF:          5.3.2
I (558) efuse_init: Min chip rev:     v0.0
I (562) efuse_init: Max chip rev:     v0.99
I (567) efuse_init: Chip rev:         v0.1
I (572) heap_init: Initializing. RAM available for dynamic allocation:
I (579) heap_init: At 408171E0 len 000361A0 (216 KiB): RAM
I (586) heap_init: At 4084D380 len 00002B60 (10 KiB): RAM
I (593) spi_flash: detected chip: generic
I (596) spi_flash: flash io: dio
W (601) i2c: This driver is an old driver, please migrate your application code to adapt `driver/i2c_master.h`
I (611) sleep: Configure to isolate all GPIO pins in sleep state
I (618) sleep: Enable automatic switching of GPIO sleep configuration
I (625) main_task: Started on CPU0
I (641) main_task: Calling app_main()
[I][logger:171]: Log initialized
                                [C][safe_mode:080]: There have been 3 suspected unsuccessful boot attempts
                                                                                                          [D][esp32.preferences:142]: Writing 1 items: 0 cached, 1 written, 0 failed
                                                                                                                                                                                    [I][app:048]: Running through setup()
                            [C][i2c.idf:021]: Running setup
                                                           [I][i2c.idf:262]: Performing bus recovery
                                                                                                    [D][esp-idf:000]: I (803) gpio: GPIO[26]| InputEn: 1| OutputEn: 1| OpenDrain: 1| Pullup: 1| Pulldown: 0| Intr:0
                       [D][esp-idf:000]: I (806) gpio: GPIO[27]| InputEn: 1| OutputEn: 1| OpenDrain: 1| Pullup: 1| Pulldown: 0| Intr:0
```
After installing 'Timeout' on 10ms, the firmware is loaded, but the i2C does not work.

**Comment by randybb** [comment]
duplicate of https://github.com/esphome/issues/issues/6365 and a proposed fix https://github.com/esphome/esphome/pull/7077 (older than that issue)
But I think somebody mentioned it is an upstream problem and it is fixed in esp-idf 5.3.4

**Comment by ximex** [comment]
yes, @swoboda1337 wrote it's an upstream problem in esp-idf and is fixed in 5.3.4 or 5.4.2 (both not released yet). the new problem in esphome 3.6.0 is from the update of esp-idf to 5.3.2.
we need to wait until esp-idf releases a fixed version. in the meanwhile there are also ideas to set `scan: false` automatically for problematic cases. for now set `scan: false` manually

**Comment by ireun** [comment]
@ximex it would also be good to at least provide a warning for C6 and H2 versions in 2025.6.0 changelog. This was not a problem for me, but for ESP32 hidden in obscure or remote places it may make someone's day a little less enjoyable ;)

**Comment by DAVe3283** [comment]
I see this same issues on an Olimex ESP32-C6-EVB. Stack trace as requested:

<details><summary>Stack Trace</summary>

```
[14:55:40]ESP-ROM:esp32c6-20220919
[14:55:40]Build:Sep 19 2022
[14:55:40]rst:0xc (SW_CPU),boot:0x7f (SPI_FAST_FLASH_BOOT)
[14:55:40]Saved PC:0x4001975a
[14:55:40]SPIWP:0xee
[14:55:40]mode:DIO, clock div:2
[14:55:40]load:0x40875720,len:0x18ec
[14:55:40]load:0x4086c110,len:0xd9c
[14:55:40]load:0x4086e610,len:0x2f80
[14:55:40]entry 0x4086c110
[14:55:40]I (22) boot: ESP-IDF 5.3.2 2nd stage bootloader
[14:55:40]I (22) boot: compile time Jun 19 2025 14:54:36
[14:55:40]I (23) boot: chip revision: v0.0
[14:55:40]I (23) boot: efuse block revision: v0.1
[14:55:40]I (24) boot.esp32c6: SPI Speed      : 80MHz
[14:55:40]I (24) boot.esp32c6: SPI Mode       : DIO
[14:55:40]I (25) boot.esp32c6: SPI Flash Size : 4MB
[14:55:40]I (290) esp_image: segment 3: paddr=000b8944 vaddr=40801508 size=1b22ch (111148) load
[14:55:40]I (349) boot: Loaded app from partition at offset 0x10000
[14:55:40]I (349) boot: Disabling RNG early entropy source...
[14:55:40]I (351) cpu_start: Unicore app
[14:55:40]I (360) cpu_start: Pro cpu start user code
[14:55:40]I (360) cpu_start: cpu freq: 160000000 Hz
[14:55:40]I (360) app_init: Application information:
[14:55:40]I (360) app_init: Project name:     esp32c6
[14:55:40]I (361) app_init: App version:      2025.7.0-dev
[14:55:40]I (361) app_init: Compile time:     Jun 19 2025 14:53:54
[14:55:40]I (361) app_init: ELF file SHA256:  26ce05b0e...
[14:55:40]I (361) app_init: ESP-IDF:          5.3.2
[14:55:40]I (362) efuse_init: Min chip rev:     v0.0
[14:55:40]I (362) efuse_init: Max chip rev:     v0.99
[14:55:40]I (362) efuse_init: Chip rev:         v0.0
[14:55:40]I (362) heap_init: Initializing. RAM available for dynamic allocation:
[14:55:40]I (363) heap_init: At 40821F80 len 0005A690 (361 KiB): RAM
[14:55:40]I (363) heap_init: At 4087C610 len 00002F54 (11 KiB): RAM
[14:55:40]I (364) heap_init: At 50000000 len 00003FE8 (15 KiB): RTCRAM
[14:55:40]I (365) spi_flash: detected chip: generic
[14:55:40]I (365) spi_flash: flash io: dio
[14:55:40]W (365) i2c: This driver is an old driver, please migrate your application code to adapt `driver/i2c_master.h`
[14:55:40]I (366) sleep: Configure to isolate all GPIO pins in sleep state
[14:55:40]I (366) sleep: Enable automatic switching of GPIO sleep configuration
[14:55:40]I (367) coexist: coex firmware version: cbb41d7
[14:55:40]I (367) coexist: coexist rom version 5b8dcfa
[14:55:40]I (367) main_task: Started on CPU0
[14:55:40]I (367) main_task: Calling app_main()
[14:55:40][I][logger:171]: Log initialized
[14:55:40][I][app:048]: Running through setup()
[14:55:40][V][app:049]: Sorting components by setup priority
[14:55:40][C][i2c.idf:021]: Running setup
[14:55:40][I][i2c.idf:262]: Performing bus recovery
[14:55:40][VV][esp-idf:000]: I (466) gpio: GPIO[7]| InputEn: 1| OutputEn: 1| OpenDrain: 1| Pullup: 1| Pulldown: 0| Intr:0
[14:55:40][VV][esp-idf:000]: I (466) gpio: GPIO[6]| InputEn: 1| OutputEn: 1| OpenDrain: 1| Pullup: 1| Pulldown: 0| Intr:0
[14:55:40][V][i2c.idf:078]: Scanning bus for active devices
[14:55:40][VV][i2c.idf:207]: 0x08 TX
[14:55:40][VV][i2c.idf:246]: TX to 08 failed: not acked
[14:55:40][VV][i2c.idf:207]: 0x09 TX
[14:55:40][VV][i2c.idf:246]: TX to 09 failed: not acked
[14:55:40][VV][i2c.idf:207]: 0x0A TX
[14:55:40][VV][i2c.idf:246]: TX to 0A failed: not acked
[14:55:40][VV][i2c.idf:207]: 0x0B TX
[14:55:40][VV][i2c.idf:246]: TX to 0B failed: not acked
[14:55:40][VV][i2c.idf:207]: 0x0C TX
[14:55:40][VV][i2c.idf:246]: TX to 0C failed: not acked
[14:55:40][VV][i2c.idf:207]: 0x0D TX
[14:55:40][VV][i2c.idf:246]: TX to 0D failed: not acked
[14:55:40][VV][i2c.idf:207]: 0x0E TX
[14:55:40][VV][i2c.idf:246]: TX to 0E failed: not acked
[14:55:40][VV][i2c.idf:207]: 0x0F TX
[14:55:40][VV][i2c.idf:246]: TX to 0F failed: not acked
[14:55:40][VV][i2c.idf:207]: 0x10 TX
[14:55:40][VV][i2c.idf:246]: TX to 10 failed: not acked
[14:55:40][VV][i2c.idf:207]: 0x11 TX
[14:55:45]E (5465) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
[14:55:45]E (5465) task_wdt:  - loopTask (CPU 0)
[14:55:45]E (5465) task_wdt: Tasks currently running:
[14:55:45]E (5465) task_wdt: CPU 0: loopTask
[14:55:45]E (5465) task_wdt: Aborting.


[14:55:45]Core  0 register dump:
[14:55:45]MEPC    : 0x42012fac  RA      : 0x420140ba  SP      : 0x4082a2e0  GP      : 0x40819454
WARNING Decoded 0x42012fac: i2c_ll_master_is_bus_clear_done at /home/dave3283/.platformio/packages/framework-espidf@src-c44434145e05010467d5d5a727b42ef9/components/hal/esp32c6/include/hal/i2c_ll.h:779
 (inlined by) i2c_master_clear_bus at /home/dave3283/.platformio/packages/framework-espidf@src-c44434145e05010467d5d5a727b42ef9/components/driver/i2c/i2c.c:688
 (inlined by) i2c_hw_fsm_reset at /home/dave3283/.platformio/packages/framework-espidf@src-c44434145e05010467d5d5a727b42ef9/components/driver/i2c/i2c.c:722
WARNING Decoded 0x42012fac: i2c_ll_master_is_bus_clear_done at /home/dave3283/.platformio/packages/framework-espidf@src-c44434145e05010467d5d5a727b42ef9/components/hal/esp32c6/include/hal/i2c_ll.h:779
 (inlined by) i2c_master_clear_bus at /home/dave3283/.platformio/packages/framework-espidf@src-c44434145e05010467d5d5a727b42ef9/components/driver/i2c/i2c.c:688
 (inlined by) i2c_hw_fsm_reset at /home/dave3283/.platformio/packages/framework-espidf@src-c44434145e05010467d5d5a727b42ef9/components/driver/i2c/i2c.c:722
[14:55:45]TP      : 0x4082a430  T0      : 0x00000000  T1      : 0x40000044  T2      : 0x07800000
[14:55:45]S0/FP   : 0x00000000  S1      : 0x4082b880  A0      : 0x00000000  A1      : 0x4082b370
[14:55:45]A2      : 0x00000001  A3      : 0x00000800  A4      : 0x00000013  A5      : 0x60004000
[14:55:45]A6      : 0x00000004  A7      : 0x00000014  S2      : 0x00000000  S3      : 0x0000007f
[14:55:45]S4      : 0x00000014  S5      : 0x0000006b  S6      : 0x000003e8  S7      : 0x00000000
[14:55:45]S8      : 0x4209f000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
[14:55:45]T3      : 0x40822000  T4      : 0x00000001  T5      : 0x40822000  T6      : 0x00000001
[14:55:45]MSTATUS : 0x00000000  MTVEC   : 0x408241f4  MCAUSE  : 0x00000011  MTVAL   : 0x00000001
[14:55:45]MHARTID : 0x00000001

[14:55:45]Stack memory:
[14:55:45]4082a2e0: 0x00000000 0x408241f4 0x00000011 0x00000001 0x00000001 0x00000000 0x4082b458 0x42090000
[14:55:45]4082a300: 0x00000000 0x408241f4 0x00000011 0x42002018 0x00000000 0x00000000 0x4082a320 0x00000000
[14:55:45]4082a320: 0x00000000 0x0000000a 0x4082b45c 0x00000078 0x00000006 0x00000001 0x00000000 0x00000002
[14:55:45]4082a340: 0x00000008 0x00000001 0x00000006 0x00000078 0x4082b45c 0x4082b458 0x00000011 0x420017f8
[14:55:45]4082a360: 0x00000001 0x40821c6c 0x40818d0c 0x4011a380 0x00000008 0x00000008 0x42092000 0x4082b46c
[14:55:45]4082a380: 0x00000001 0x42090000 0x4082b458 0x42001b2e 0x4081c74c 0x00000001 0x00000006 0x00000007
[14:55:45]4082a3a0: 0x00000101 0x0000c350 0x00000000 0x00000000 0x00000001 0x4082a60c 0x4081c74c 0x420093da
[14:55:45]4082a3c0: 0x00000000 0x00000007 0x00000007 0x4082b880 0x00000000 0x00000000 0x00000000 0x00000000
[14:55:45]4082a3e0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x420002cc
[14:55:45]4082a400: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[14:55:45]4082a420: 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000150 0x4082a260
[14:55:45]4082a440: 0x0000007f 0x4081d2e8 0x4081d2e8 0x4082a43c 0x4081d2e0 0x00000018 0x4082b974 0x4082b974
[14:55:45]4082a460: 0x4082a43c 0x00000000 0x00000001 0x40828438 0x706f6f6c 0x6b736154 0x00000000 0x00000000
[14:55:45]4082a480: 0x4082a430 0x00000001 0x00000001 0x00000000 0x00000000 0x00000000 0x408229b8 0x40822a20
[14:55:45]4082a4a0: 0x40822a88 0x00000000 0x00000000 0x00000001 0x00000000 0x00000000 0x00000000 0x4202e3f0
[14:55:45]4082a4c0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[14:55:45]4082a4e0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[14:55:45]4082a500: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[14:55:45]4082a520: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[14:55:45]4082a540: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[14:55:45]4082a560: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
[14:55:45]4082a580: 0x00000000 0x00000000 0x00000000 0x00000010 0x4082b49c 0x4082b518 0x4082b594 0x4082b610
[14:55:45]4082a5a0: 0x00000014 0x4082b68c 0x4082b6f0 0x4082b754 0x4082b7b8 0x4082b81c 0x00000014 0x4082b190
[14:55:45]4082a5c0: 0x00000000 0x32335053 0x2d36432d 0x4082a5b4 0x00000010 0x00000000 0x4082a43c 0x00000000
[14:55:45]4082a5e0: 0x00000000 0x00000020 0x6d696c4f 0x45207865 0x32335053 0x2d36432d 0x00425645 0xa5a5a5a5
[14:55:45]4082a600: 0xa5a5a5a5 0x4082a5e0 0x00000038 0x4082a648 0x4082b46c 0x4082b350 0x4082b4d4 0x4082b550
[14:55:45]4082a620: 0x4082b5cc 0x4082b648 0x4082b6bc 0x4082b720 0x4082b784 0x4082b7e8 0x4082b84c 0x4082b1f8
[14:55:45]4082a640: 0x4082b410 0x00000070 0x420a1f0c 0x7fc00000 0x42090ae8 0x00000000 0x00010032 0x0001c200
[14:55:45]4082a660: 0x4082a6bc 0x00000026 0x00000200 0x00000003 0x00000000 0xa5a5a5a5 0x00000000 0x00000000
[14:55:45]4082a680: 0x4082a678 0x4082a678 0x00000000 0x00000000 0x00000000 0x00000000 0x00000007 0x4082a8c4
[14:55:45]4082a6a0: 0xa5a5a500 0x00000003 0x00000000 0x00000000 0x00000000 0x4082a43c 0x00000204 0x3b305b1b
[14:55:45]4082a6c0: 0x5b6d3833 0x5b5d5656 0x2e633269 0x3a666469 0x5d373032 0x7830203a 0x54203131 0x5b1b2058



[14:55:45]ELF file SHA256: 26ce05b0e

[14:55:45]Rebooting...
```
</details>

<details><summary>Device YAML</summary>

```yaml
esphome:
  name: esp32c6
  friendly_name: Olimex ESP32-C6-EVB

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf

logger:
  hardware_uart: USB_SERIAL_JTAG # Use native USB C port
  level: VERY_VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

i2c:
  sda: 6
  scl: 7

switch:
  - platform: gpio
    pin: 10
    name: REL1
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 11
    name: REL2
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 22
    name: REL3
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 23
    name: REL4
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    name: BUT1
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
  - platform: gpio
    name: OPT1
    pin:
      number: 1
      inverted: true
  - platform: gpio
    name: OPT2
    pin:
      number: 2
      inverted: true
  - platform: gpio
    name: OPT3
    pin:
      number: 3
      inverted: true
  - platform: gpio
    name: OPT4
    pin:
      number: 15
      inverted: true
```
<details>

**Comment by yanekxd** [comment]
Hi, I can confirm this issue on a Seeed XIAO ESP32-C6 using ESPHome 2025.6.0.

I am experiencing the exact same WDT crash with a backtrace pointing to `i2c_ll_master_is_bus_clear_done`. The issue occurs with a clean flash and no devices connected to the I2C pins.

I also tried the temporary fix suggested in issue esphome/issues#6932 by adding the following to my configuration:

```
yaml
external_components:
  - source: github://esphome/esphome@pull/6932/head
    components: [ i2c ]
```

Unfortunately, even after a full clean recompile and flash, the issue persists with the exact same crash log and backtrace. This suggests that the fix in PR esphome/issues#6932 might not cover the espidf framework used by the ESP32-C6, or the issue lies deeper.

I'm attaching my latest log file for reference.

[log.txt](https://github.com/user-attachments/files/20848563/log.txt)

**Comment by swoboda1337** [comment]
> Hi, I can confirm this issue on a Seeed XIAO ESP32-C6 using ESPHome 2025.6.0.
> 

The issue is well understood and already fixed in later IDF versions. For now disable scan. If you really want scan use 5.5 (its not officially released, this is a beta of sorts):
```
esp32:
  framework:
    type: esp-idf
    version: 5.5.0
    release: "20250510"
    platform_version: "https://github.com/pioarduino/platform-espressif32.git#develop"
```

**Comment by derMicro** [comment]
**This error does not only affect the C6**, the ESP32-S3, at least in the Waveshare 7" Touch Display, is also affected. However, the ESP32 only crashes when the device is restarted; if the power supply is interrupted, the ESP starts properly.
Setting “scan:false” also solves the problem here.

```
[19:57:34]ESP-ROM:esp32s3-20210327
[19:57:34]Build:Mar 27 2021
[19:57:34]rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[19:57:34]Saved PC:0x40043ac8
[19:57:34]SPIWP:0xee
[19:57:34]mode:DIO, clock div:1
[19:57:34]load:0x3fce2820,len:0x19fc
[19:57:34]load:0x3c870000,len:0x4ff
[19:57:34]Invalid image block, can't boot.
[19:57:34]ets_main.c 329
```


EDIT:
Oh no, unfortunately the reboot only worked once, now the ESP crashes again when you trigger a reboot.

**Comment by swoboda1337** [comment]
> **This error does not only affect the C6**, the ESP32-S3, at least in the Waveshare 7" Touch Display, is also affected. 

Yeah I was afraid of that. All devices except the original ESP32 have SOC_I2C_SUPPORT_HW_CLR_BUS defined and could get stuck in an infinite loop.

**Comment by derMicro** [comment]
> The issue is well understood and already fixed in later IDF versions. For now disable scan. If you really want scan use 5.5 (its not officially released, this is a beta of sorts):
> 
> ```
> esp32:
>   framework:
>     type: esp-idf
>     version: 5.5.0
>     release: "20250510"
>     platform_version: "https://github.com/pioarduino/platform-espressif32.git#develop"
> ```

Too bad, unfortunately this did not work with the ESP32-S3. As I said, the crash only happens when a restart is triggered, and only since 2025.6
The problem never occurred the months before, as I restart all my LVGL displays every day at 12 noon, experience shows that LVGL then runs more efficiently.

But, let's turn off the automatic reboot for now, we'll get the problem solved ;)

**Comment by JochenFriedrich** [comment]
On a ESP-C6 device with zigbee external component and AHT20 / BMP280 sensor combo, it was enough to increase the i2c frequency to 100kHz to get rid of the boot loop.

On the other hand, 5.5.0 really fixes a truckload of problems on C6 and probably H2, as well.

remote_receiver with cc1101 or sx127x in 433.920 MHz OOK mode crashes every few seconds on earlier idf versions on these chips.

**Comment by swoboda1337** [comment]
> remote_receiver with cc1101 or sx127x in 433.920 MHz OOK mode crashes every few seconds on earlier idf versions on these chips.

Interesting, I havent seen any remote_receiver issues on 5.3.2 but I always run with these configs:
```
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_CONSOLE_NONE: "y"
      CONFIG_RMT_RECV_FUNC_IN_IRAM: "y"
      CONFIG_RMT_ISR_IRAM_SAFE: "y"
```

**Comment by JochenFriedrich** [comment]
It's on ESP32-C6. On all other chips (I didn't test H2), It's working without issues. Even on ESP8266.

Looks like this was the culprit:

https://github.com/espressif/esp-idf/commit/fac2d9eada10307fa0c2f8c479696cce5a6a43d1

**Comment by swoboda1337** [comment]
> It's on ESP32-C6. On all other chips (I didn't test H2), It's working without issues. Even on ESP8266.
> 
> Looks like this was the culprit:
> 
> [espressif/esp-idf@fac2d9e](https://github.com/espressif/esp-idf/commit/fac2d9eada10307fa0c2f8c479696cce5a6a43d1)

Interesting. You can also try 5.4.2 with https://github.com/esphome/esphome/pull/9243 make sure to clean everything though

**Comment by ireun** [comment]
@jesserockz i don't think this issue should be closed..

**Comment by jesserockz** [comment]
You're right, the underlying issue is not solved, it was just made so a default config will not crash any longer.

**Comment by derMicro** [comment]
> **This error does not only affect the C6**, the ESP32-S3, at least in the Waveshare 7" Touch Display, is also affected. However, the ESP32 only crashes when the device is restarted; if the power supply is interrupted, the ESP starts properly. Setting “scan:false” also solves the problem here.
> 
> ```
> [19:57:34]ESP-ROM:esp32s3-20210327
> [19:57:34]Build:Mar 27 2021
> [19:57:34]rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
> [19:57:34]Saved PC:0x40043ac8
> [19:57:34]SPIWP:0xee
> [19:57:34]mode:DIO, clock div:1
> [19:57:34]load:0x3fce2820,len:0x19fc
> [19:57:34]load:0x3c870000,len:0x4ff
> [19:57:34]Invalid image block, can't boot.
> [19:57:34]ets_main.c 329
> ```
> 
> EDIT: Oh no, unfortunately the reboot only worked once, now the ESP crashes again when you trigger a reboot.

In version 2025.6.3 the ESP32-S3 still crashes when it is rebooted. However, a cold start (reconnect power) is not a problem.
Unfortunately I cannot deactivate I2C because then the display or touch of the Waveshare 7" display will no longer work.

Config:

```
esphome:
  platformio_options:
    build_unflags: -Werror=all
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: qio
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_ESPTOOLPY_FLASHFREQ_120M: y
      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_IDF_EXPERIMENTAL_FEATURES: y
      CONFIG_SPIRAM_SPEED_120M: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_COMPILER_OPTIMIZATION_PERF: y
      CONFIG_LV_MEM_CUSTOM: y
      CONFIG_LV_MEMCPY_MEMSET_STD: y
      CONFIG_LV_ATTRIBUTE_FAST_MEM: y
    advanced:
      enable_idf_experimental_features: true

psram:
  mode: octal
  speed: 120MHz
    
i2c:
  - id: i2c_bus
    sda: GPIO08
    scl: GPIO09
    scan: false

# spi:
#   - id: spi_bus
#     clk_pin: GPIO41
#     mosi_pin: GPIO48

ch422g:
  - id: ch422g_hub

touchscreen:
  platform: gt911
  id: lcd7_touchscreen
  interrupt_pin: GPIO4
  reset_pin:
    ch422g: ch422g_hub
    number: 1
    mode: OUTPUT
  on_touch:
    - script.stop: start_scr
  on_release:
    - light.turn_on:
        id: id_light_backlight_brightness
        brightness: 100%
    - lvgl.page.show: page_main
    - script.execute: start_scr

output:
  - platform: ledc
    pin: GPIO16
    id: id_output_backlight_brightness
    min_power: 0.08

light:
  - platform: monochromatic
    id: id_light_backlight_brightness
    output: id_output_backlight_brightness
    name: "Backlight Brightness"
    restore_mode: ALWAYS_ON

switch:
  - platform: gpio
    id: lcdbacklight
    name: "LCD Backlight"
    internal: true
    pin:
      ch422g: ch422g_hub
      number: 2
      mode:
        output: true
      inverted: false
    restore_mode: ALWAYS_ON

display:
  - platform: rpi_dpi_rgb
    id: lcd7_display
    auto_clear_enabled: false
    color_order: RGB
    pclk_frequency: 16MHz
    dimensions:
      width: 800
      height: 480
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    hsync_back_porch: 30
    hsync_front_porch: 210
    hsync_pulse_width: 30
    vsync_back_porch: 4
    vsync_front_porch: 4
    vsync_pulse_width: 4
    data_pins:
      red:
        - 1         #r3
        - 2         #r4
        - 42        #r5
        - 41        #r6
        - 40        #r7
      blue:
        - 14        #b3
        - 38        #b4
        - 18        #b5
        - 17        #b6
        - 10        #b7
      green:
        - 39        #g2
        - 0         #g3
        - 45        #g4
        - 48        #g5
        - 47        #g6
        - 21        #g7
```

**Comment by ximex** [comment]
Hopefully with 2025.8.0 esphome updates to ESP-IDF 5.4.2 (by default) where the bug should be fixed

**Comment by swoboda1337** [comment]
With 2025.7 you will be able to use 5.4.2 by doing:
```
esp32:
  framework:
    type: esp-idf
    version: 5.4.2
    platform_version: 54.03.21
```

**Comment by derMicro** [comment]
I will test 5.4.2 when the UART compile error that came with 2025.7 is fixed.

Edit: 
It was a bug in the Homeassistant API Component, which was fixed with .1
Now i can test with Version 5.4.2

**Comment by derMicro** [comment]
> With 2025.7 you will be able to use 5.4.2 by doing:
> 
> ```
> esp32:
>   framework:
>     type: esp-idf
>     version: 5.4.2
>     platform_version: 54.03.21
> ```

No, unfortunately still the problem.

With ESP 5.4.2 and ESPHome 2025.7.1 the ESP32-S3 still crashes when you trigger a reboot. However, briefly removing the power works and the ESP starts normally.

Any ideas what else I can try apart from disabling I2C which will disable the display and touch as well?

**Comment by ireun** [comment]
@derMicro do you need I2C scan? Why not just disable it?

**Comment by swoboda1337** [comment]
What is the crash? Do you have a log?

**Comment by derMicro** [comment]
> [@derMicro](https://github.com/derMicro) do you need I2C scan? Why not just disable it?

I had already deactivated the scan when I created the first comment on this issue.

**Comment by derMicro** [comment]
> What is the crash? Do you have a log?

One moment, I connect the display via USB, the only chance to see the errors.

EDIT:
```
[19:14:15]ESP-ROM:esp32s3-20210327
[19:14:16]ESP-ROM:esp32s3-20210327
[19:14:16]Build:Mar 27 2021
[19:14:16]rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[19:14:16]Saved PC:0x40043ac8
[19:14:16]SPIWP:0xee
[19:14:16]mode:DIO, clock div:1
[19:14:16]load:0x3fce2820,len:0x19fc
[19:14:16]load:0x3c870000,len:0x4ff
[19:14:16]Invalid image block, can't boot.
[19:14:16]ets_main.c 329 
Terminal disconnected: NetworkError: The device has been lost.
```
More is not displayed

**Comment by ireun** [comment]
> I had already deactivated the scan when I created the first comment on this issue.

Then that's another issue, this one talks only about bootloop with `scan: true` on C6 and other models

**Comment by derMicro** [comment]
> > I had already deactivated the scan when I created the first comment on this issue.
> 
> Then that's another issue, this one talks only about bootloop with `scan: true` on C6 and other models

I can't judge that, I only know that this behavior has occurred since version 2025.6.0 and that my error message seems to be identical to the last lines of the problem creator.

**Comment by derMicro** [comment]
Oh, that's even crazier now, if I have the ESPHome log window open while the device is working and connected to USB, and I press Edit or Close then the ESP also crashes. This is new.

If I open the log window via Wifi this does not happen.

**Comment by derMicro** [comment]
Ok...after many tests I was able to solve it, after changing the model from esp32-s3-devkitc-1 to esp32s3box and some adjustments to the PSRAM the reboot now works again. However, there is again this crazy flickering on the display during the flash process.

Obviously there are some changes in the ESPHome code, which in my opinion cannot be related to ESP-IDF, because when version 2025.6 was released, I switched back to ESP 5.3.1 and platform 6.9.0 and the reboot problem remained, which did not exist with the same IDF and platform until 2025.5.

**Comment by swoboda1337** [comment]
> Ok...after many tests I was able to solve it, after changing the model from esp32-s3-devkitc-1 to esp32s3box and some adjustments to the PSRAM the reboot now works again. However, there is again this crazy flickering on the display during the flash process.
> 
> Obviously there are some changes in the ESPHome code, which in my opinion cannot be related to ESP-IDF, because when version 2025.6 was released, I switched back to ESP 5.3.1 and platform 6.9.0 and the reboot problem remained, which did not exist with the same IDF and platform until 2025.5.

You are running the cores at 240mhz?

**Comment by derMicro** [comment]
Yes, without setting the CPU to 240Mhz, compiling has failed since 2025.6
According to the manufacturer, the display runs best with 120Mhz PSRAM Octal, which I have now set to 80Mhz.

**Comment by derMicro** [comment]
Ok, so far I have returned to my old config but without 120Mhz PSRAM. The flickering of the display during flashing is also gone again.

```
esphome:
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: qio
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32s3box
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: 5.4.2
    platform_version: 54.03.21
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_LV_MEM_CUSTOM: y
      CONFIG_LV_MEMCPY_MEMSET_STD: y
      CONFIG_LV_ATTRIBUTE_FAST_MEM: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_LV_DISP_DEF_REFR_PERIOD: "10"

psram:
  mode: octal
  speed: 80MHz
```

After setting these 3 parameters, the flickering was gone.
```
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_SPIRAM_MODE_OCT: y
```

**Comment by bennydiamond** [comment]
I just wanted to say that setting the following custom IDF version fixed my issues I've been having on my Waveshare ESP32-S3-Touch-LCD-7 since 2025.6.x

```
    version: 5.4.2
    platform_version: 54.03.21
```

thanks!

**Comment by ximex** [comment]
@ireun could you retest with 2025.8.0-beta.1?

**Comment by swoboda1337** [comment]
Should be fixed in 2025.8
